// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shoppe.Model.EFStructures;

#nullable disable

namespace Model.EfStructures.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shoppe.Model.Entities.CuaHang", b =>
                {
                    b.Property<string>("IdCuaHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenCuaHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("UrlAnh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCuaHang");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("CuaHang");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.DanhGia", b =>
                {
                    b.Property<string>("IdDanhGia")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("DiemDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("ThoiGianDg")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianDG");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdNguoiDung");

                    b.HasIndex("IdSanPham");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.DonHang", b =>
                {
                    b.Property<string>("IdDonHang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("IdLienHe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdSanPham")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianGiao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdDonHang");

                    b.HasIndex("IdLienHe");

                    b.HasIndex("IdSanPham");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.NguoiDung", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)")
                        .HasColumnName("CCCD");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.SanPham", b =>
                {
                    b.Property<string>("IdSanPham")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaGoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("IdCuaHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdDanhMuc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime");

                    b.Property<int>("TongDiemGiaBan")
                        .HasColumnType("int")
                        .HasColumnName("TongDIemGiaBan");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("UrlAnh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSanPham");

                    b.HasIndex("IdCuaHang");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.ThanhToan", b =>
                {
                    b.Property<string>("IdThanhToan")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdDonHang")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("LoaiThanhToan")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("datetime");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdThanhToan");

                    b.HasIndex("IdDonHang");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.ThongTinLienHe", b =>
                {
                    b.Property<string>("IdLienHe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.HasKey("IdLienHe");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("ThongTinLienHe");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.CuaHang", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("CuaHangs")
                        .HasForeignKey("IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_CuaHang_NguoiDung");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.DanhGia", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_DanhGia_NguoiDung");

                    b.HasOne("Shoppe.Model.Entities.SanPham", "IdSanPhamNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_DanhGia_SanPham");

                    b.Navigation("IdNguoiDungNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.DonHang", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.ThongTinLienHe", "IdLienHeNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdLienHe")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_ThongTinLienHe");

                    b.HasOne("Shoppe.Model.Entities.SanPham", "IdSanPhamNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("IdSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_SanPham");

                    b.Navigation("IdLienHeNavigation");

                    b.Navigation("IdSanPhamNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.SanPham", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.CuaHang", "IdCuaHangNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdCuaHang")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_CuaHang");

                    b.Navigation("IdCuaHangNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.TaiKhoan", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.NguoiDung", "IdNguoiDungNavigation")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("Shoppe.Model.Entities.TaiKhoan", "IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_TaiKhoan_NguoiDung");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.ThanhToan", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.DonHang", "IdDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("IdDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_DonHang");

                    b.Navigation("IdDonHangNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.ThongTinLienHe", b =>
                {
                    b.HasOne("Shoppe.Model.Entities.NguoiDung", "IdNguoiDungNavigation")
                        .WithMany("ThongTinLienHes")
                        .HasForeignKey("IdNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_ThongTinLienHe_NguoiDung");

                    b.Navigation("IdNguoiDungNavigation");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.CuaHang", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.DonHang", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.NguoiDung", b =>
                {
                    b.Navigation("CuaHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("TaiKhoan");

                    b.Navigation("ThongTinLienHes");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.SanPham", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("Shoppe.Model.Entities.ThongTinLienHe", b =>
                {
                    b.Navigation("DonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
